Add README.rst validation to the lint testenv
RIOT-OS/riotctrl pull request #26
Opened 2021-09-21 11:30 UTC by aabadie

As described [here](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup), using twine it's possible to validate the rST Markup language of the README.

This PR adds a new command that does that to the Tox lint testenv.

This is based on #25

2021-09-21 15:41 UTC, miri64 approved these changes

2021-09-21 15:46 UTC, aabadie commented
rebased

2021-09-21 15:47 UTC, miri64 submitted a review, later dismissed

2021-09-21 15:52 UTC, aabadie commented
When do we drop Python 3.5 support ? ;)

2021-09-21 15:53 UTC, miri64 commented
Ask @kaspar030 or help him update his Raspberry Pis ;-).

2021-09-21 15:56 UTC, aabadie commented
> We can also drop --strict option from Twine until then if you want

Without this option and without 887f8b0, this check would have raised a warning but not fail.

2021-09-22 10:38 UTC, miri64 requested changes

2021-09-22 10:54 UTC, aabadie commented on tox.ini
> +    twine check {distdir}/*
One possibility is to add a tox testenv just for this and call it in the gh action only if python is 3.9. Would you be ok with that ?

2021-09-22 10:55 UTC, aabadie commented on tox.ini
> +    twine check {distdir}/*
Because in the end, the package is generated only for python 3.9, so having a valid README markup only matters for this version.

2021-09-22 10:58 UTC, miri64 commented on tox.ini
> +    twine check {distdir}/*
:+1: I think having an extra `testenv` for this would be cleaner anyways.

2021-09-22 12:10 UTC, aabadie commented on tox.ini
> +    twine check {distdir}/*
Done

2021-09-22 14:01 UTC, miri64 approved these changes

2021-09-22 14:01 UTC, merged